import { useEffect, useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Modal } from '@/components/ui/Modal';
import { Input } from '@/components/ui/Input';
import { Select } from '@/components/ui/Select';
import { Button } from '@/components/ui/Button';
import { useAcademiaStore } from '@/store/useAcademiaStore';

const courseSchema = z.object({
  departmentId: z.string().min(1, 'Department is required'),
  title: z.string().min(3, 'Course title is required'),
});

type CourseFormData = z.infer<typeof courseSchema>;

export function AddCourseModal() {
  const { isCourseModalOpen, setCourseModalOpen, addCourse, departments, faculties } = useAcademiaStore();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);

  const { register, handleSubmit, watch, formState: { errors }, reset } = useForm<CourseFormData>({
    resolver: zodResolver(courseSchema),
    defaultValues: { departmentId: '', title: '' },
  });

  useEffect(() => {
    if (isCourseModalOpen) {
      reset();
      setSubmitError(null);
    }
  }, [isCourseModalOpen, reset]);

  const selectedDeptId = watch('departmentId');
  // Auto-derive faculty from the selected department
  const derivedFacultyId = departments.find((d) => d.id === selectedDeptId)?.facultyId ?? '';

  const onSubmit = async (data: CourseFormData) => {
    if (!derivedFacultyId) {
      setSubmitError('Selected department has no linked faculty. Please check your data.');
      return;
    }
    setIsSubmitting(true);
    setSubmitError(null);
    try {
      await addCourse({
        facultyId: derivedFacultyId,
        departmentId: data.departmentId,
        title: data.title,
        code: '',  // auto-generated by backend
      });
      reset();
      setCourseModalOpen(false);
    } catch (error: any) {
      const msg =
        error?.response?.data?.detail ??
        error?.response?.data?.error?.message ??
        error?.message ??
        'Failed to create course. Please try again.';
      setSubmitError(msg);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <Modal isOpen={isCourseModalOpen} onClose={() => setCourseModalOpen(false)} title="Create Course" className="md:max-w-md">
      <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
        {submitError && (
          <div className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700 dark:border-rose-500/20 dark:bg-rose-500/10 dark:text-rose-200">
            {submitError}
          </div>
        )}

        <div>
          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1.5 ml-1">Department</label>
          <Select
            options={[
              { value: '', label: 'Select Department...' },
              ...departments.map((d) => ({ value: d.id, label: d.name })),
            ]}
            {...register('departmentId')}
            error={errors.departmentId?.message}
          />
          {selectedDeptId && derivedFacultyId && (
            <p className="text-xs text-gray-400 mt-1 ml-1">
              Faculty: {faculties.find((f) => f.id === derivedFacultyId)?.name ?? derivedFacultyId}
            </p>
          )}
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1.5 ml-1">Course Title</label>
          <Input
            placeholder="e.g. Introduction to Computer Science"
            {...register('title')}
            error={errors.title?.message}
          />
          <p className="text-xs text-gray-400 mt-1 ml-1">Course code is generated automatically by the system.</p>
        </div>

        <div className="flex items-center justify-end gap-3 pt-6 mt-6">
          <Button type="button" variant="ghost" onClick={() => setCourseModalOpen(false)}>Cancel</Button>
          <Button type="submit" isLoading={isSubmitting}>Create Course</Button>
        </div>
      </form>
    </Modal>
  );
}
