"""add attendance and schedule tables

Revision ID: 5fdacb70a9f9
Revises: c2d3e4f5a6b7
Create Date: 2026-05-01 21:13:56.770902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '5fdacb70a9f9'
down_revision: Union[str, Sequence[str], None] = 'c2d3e4f5a6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=200), nullable=False),
    sa.Column('course_code', sa.String(length=32), nullable=False),
    sa.Column('classes_attended', sa.Integer(), nullable=False),
    sa.Column('total_classes', sa.Integer(), nullable=False),
    sa.Column('attendance_percentage', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('Good', 'Warning', 'Low', name='attendance_summary_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('classes_attended <= total_classes', name='ck_attendance_classes_attended_not_greater_than_total'),
    sa.CheckConstraint('classes_attended >= 0', name='ck_attendance_classes_attended_nonnegative'),
    sa.CheckConstraint('total_classes > 0', name='ck_attendance_total_classes_positive'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_course_code'), 'attendance', ['course_code'], unique=False)
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_student_id'), 'attendance', ['student_id'], unique=False)
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=200), nullable=False),
    sa.Column('course_code', sa.String(length=32), nullable=False),
    sa.Column('weekdays', sa.JSON(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('grace_period_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('grace_period_minutes >= 0', name='ck_schedule_grace_period_nonnegative'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_course_code'), 'schedule', ['course_code'], unique=False)
    op.create_index(op.f('ix_schedule_id'), 'schedule', ['id'], unique=False)
    op.create_index(op.f('ix_schedule_student_id'), 'schedule', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_student_id'), table_name='schedule')
    op.drop_index(op.f('ix_schedule_id'), table_name='schedule')
    op.drop_index(op.f('ix_schedule_course_code'), table_name='schedule')
    op.drop_table('schedule')
    op.drop_index(op.f('ix_attendance_student_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_course_code'), table_name='attendance')
    op.drop_table('attendance')
    # ### end Alembic commands ###
